spring:
  application.name: video_storage_backend
  servlet.multipart:
    max-file-size: 5MB
    max-request-size: 5MB

  jpa:
    hibernate.ddl-auto: none

activity-detector:
  video:
    folderPath: ${VIDEO_FOLDER_PATH:videos} #Sciezka wzieta ze zmiennej srodowiskowej lub jezeli jej nie ma domyslna wartosc \videos
    subfolderDepth: 1 #Liczba poziomów subfolderów w katalogu z video. 0 oznacza brak subfolderow w katalogu.

