spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/activitydetectordb
    username: user
    password: password

logging:
  level:
    com.actdet.backend: DEBUG

activity-detector:
  controllers:
    show-error-details-in-response: true
